# Generated by Django 5.1.6 on 2025-02-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250127_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_email',
            new_name='facebook_email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_name',
            new_name='facebook_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin_profile_pic',
            new_name='facebook_profile_pic',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
