# Generated by Django 5.1.6 on 2025-02-14 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_members',
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
