# Generated by Django 5.1.6 on 2025-02-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_project_team_members_project_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='excalidraw_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
