# Generated by Django 5.1.6 on 2025-02-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_project_excalidraw_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='excalidraw_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
