# Generated by Django 5.1.6 on 2025-02-19 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_project_excalidraw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='excalidraw_data',
        ),
        migrations.AddField(
            model_name='project',
            name='room_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excalidraw_data', models.JSONField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard', to='app.project')),
            ],
            options={
                'db_table': 'app_whiteboard',
            },
        ),
    ]
