# Generated by Django 5.1.6 on 2025-02-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_project_excalidraw_data_project_room_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whiteboard',
            name='excalidraw_data',
        ),
        migrations.AddField(
            model_name='whiteboard',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='whiteboard',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='whiteboard',
            table=None,
        ),
    ]
