# Generated by Django 5.1.6 on 2025-02-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_whiteboard_excalidraw_data_whiteboard_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whiteboard',
            name='data',
        ),
        migrations.AddField(
            model_name='whiteboard',
            name='drawing_data',
            field=models.JSONField(default=dict),
        ),
    ]
