# Generated by Django 5.1.6 on 2025-03-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_sms',
            field=models.BooleanField(default=False),
        ),
    ]
